# Generated by Django 4.1.1 on 2022-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_ip',
            field=models.CharField(blank=True, max_length=15, verbose_name='手机号'),
        ),
    ]
