# Generated by Django 4.1.1 on 2022-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0004_user_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='用户身份'),
        ),
    ]
