# Generated by Django 4.1.1 on 2022-09-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0006_remove_user_mobile_user_mobile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20, unique=True, verbose_name='作者编号')),
                ('author_name', models.CharField(max_length=20, verbose_name='作者名称')),
                ('CREATED_BY', models.CharField(max_length=20, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_BY', models.CharField(max_length=20, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_number', models.CharField(max_length=20, unique=True, verbose_name='小说编号')),
                ('novel_name', models.CharField(max_length=20, verbose_name='小说名称')),
                ('novel_page_count', models.IntegerField(max_length=20, verbose_name='小说当前章节数')),
                ('novel_status', models.CharField(max_length=1, verbose_name='小说当前状态')),
                ('novel_cate', models.CharField(max_length=1, verbose_name='小说分类')),
                ('novel_surface_img', models.CharField(max_length=255, verbose_name='小说封面保存地址')),
                ('novel_author', models.CharField(max_length=20, verbose_name='小说作者')),
                ('novel_description', models.CharField(max_length=255, verbose_name='小说描述')),
                ('CREATED_BY', models.CharField(max_length=20, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_BY', models.CharField(max_length=20, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True)),
                ('author_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.authors')),
            ],
            options={
                'db_table': 'novel',
            },
        ),
        migrations.CreateModel(
            name='novels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_number', models.CharField(max_length=20, verbose_name='小说编号')),
                ('novel_page_name', models.CharField(max_length=50, verbose_name='章节名称')),
                ('novel_page_num', models.CharField(max_length=20, verbose_name='章节编号')),
                ('novel_content', models.TextField(verbose_name='小说内容')),
                ('CREATED_BY', models.CharField(max_length=20, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_BY', models.CharField(max_length=20, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True)),
                ('novel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.novel')),
            ],
            options={
                'db_table': 'novels',
            },
        ),
    ]
