# Generated by Django 4.1.1 on 2022-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, unique=True, upload_to='avatar', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wxchat',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='微信号'),
        ),
    ]
